version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  ignore:
    - dependency-name: "MicrosoftMauiGraphicsVersion"
    - dependency-name: "Microsoft.Maui.Graphics*"
    - dependency-name: "Microsoft.DotNet.XHarness*"
  labels:
      - "nuget"
      - "dependencies"
      - "area/upstream"