parameters:
  androidApiLevels: [ 30, 29, 21 ]
  iosVersions: [ '14.3' ]
  projects:
    - name: essentials
      desc: Essentials
      android: $(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.Android/Essentials.DeviceTests.Android.csproj
      ios: $(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj
    - name: core
      desc: Core
      android: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj
      ios: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj

stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.android, '') }}:
          - ${{ each api in parameters.androidApiLevels }}:
            - job: android_device_tests_${{ project.name }}_${{ api }}
              workspace:
                clean: all
              displayName: ${{ coalesce(project.desc, project.name) }} (API ${{ api }})
              pool:
                name: $(vs2019VmPool)
                vmImage: $(vs2019VmImage)
              variables:
                ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis;x86"
              steps:
                - pwsh: 'gci env:*'
                - template: device-tests-steps.yml
                  parameters:
                    platform: android
                    path: ${{ project.android }}
                    device: android-emulator-32_${{ api }}

  - stage: ios_device_tests
    displayName: iOS Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.ios, '') }}:
          - ${{ each version in parameters.iosVersions }}:
            - job: ios_device_tests_${{ project.name }}_${{ replace(version, '.', '_') }}
              workspace:
                clean: all
              displayName: ${{ coalesce(project.desc, project.name) }} (v${{ version }})
              pool:
                name: $(macOSXVmPool)
                vmImage: $(macOSXVmImage)
              variables:
                ANDROID_EMULATORS: "system-images;ios-${{ version }};google_apis;x86"
              steps:
                - template: device-tests-steps.yml
                  parameters:
                    platform: ios
                    path: ${{ project.ios }}
                    device: ios-simpulator-46_${{ version }}
