parameters:
  androidApiLevels: [ 30, 29, 21 ]
  iosVersions: [ 14.3 ]
  projects:
    - name: essentials
      desc: Essentials
      platforms:
        android: $(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.Android/Essentials.DeviceTests.Android.csproj
        # - ios: $(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj
    # - name: core
    #   desc: Core
    #   platforms:
    #     # - android: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj
    #     - ios: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj
    # - name: special
    #   desc: Special
    #   platforms:
    #     - android: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj
    #     - ios: $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj


stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.platforms.android, '') }}:
          - ${{ each api in parameters.androidApiLevels }}:
            - job: device_tests_$(project.name)_$(api)
              workspace:
                clean: all
              displayName: $(project.desc) (API $(api))
              pool:
                name:  $(macOSXVmPool)
                vmImage: $(macOSXVmImage)
              variables:
                ANDROID_EMULATORS: "system-images;android-$(api);google_apis;x86"
              steps:
                - template: device-tests-steps.yml
                  parameters:
                    platform: android
                    path: $(project.platforms.android)
                    device: android-emulator-32_$(api)

  # - stage: ios_essentials
  #   displayName: Essentials (iOS)
  #   dependsOn: []
  #   jobs:
  #     - job: device_tests
  #       workspace:
  #         clean: all
  #       displayName: Device Tests
  #       pool:
  #         name:  $(macOSXVmPool)
  #         vmImage: $(macOSXVmImage)
  #       variables:
  #         devicetests.project: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj'
  #       strategy:
  #         matrix:
  #           v14_3:
  #             devicetests.device: ios-simulator-64_14.3
  #           # v10_3_1:
  #           #   devicetests.device: ios-simulator-64_10.3.1
  #       steps:
  #         - template: device-tests-steps.yml
  #           parameters:
  #             platform: ios

  # - stage: ios_handlers
  #   displayName: Handlers (iOS)
  #   dependsOn: []
  #   jobs:
  #     - job: device_tests
  #       workspace:
  #         clean: all
  #       displayName: Device Tests
  #       pool:
  #         name:  $(macOSXVmPool)
  #         vmImage: $(macOSXVmImage)
  #       variables:
  #         devicetests.project: '$(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj'
  #       strategy:
  #         matrix:
  #           v14_3:
  #             devicetests.device: ios-simulator-64_14.3
  #           # v10_3_1:
  #           #   devicetests.device: ios-simulator-64_10.3.1
  #       steps:
  #         - template: device-tests-steps.yml
  #           parameters:
  #             platform: ios
