parameters:
  androidApiLevels: [ 30, 29, 21 ]
  androidProjects:
    - job: 'essentials'
      description: 'Essentials'
      path: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.Android/Essentials.DeviceTests.Android.csproj'
    - job: 'core'
      description: 'Core'
      path: '$(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.Android/Core.DeviceTests.Android.csproj'
  # iosProjects:
  #   - $(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj
  #   - $(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj

stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.androidProjects }}:
        - ${{ each api in parameters.androidApiLevels }}:
          - job: device_tests_$(project.job)_$(api)
            workspace:
              clean: all
            displayName: $(project.description) (API $(api))
            pool:
              name:  $(macOSXVmPool)
              vmImage: $(macOSXVmImage)
            variables:
              ANDROID_EMULATORS: "system-images;android-$(api);google_apis;x86"
            steps:
              - template: device-tests-steps.yml
                parameters:
                  platform: android
                  path: $(project.path)
                  device: android-emulator-32_$(api)

  # - stage: ios_essentials
  #   displayName: Essentials (iOS)
  #   dependsOn: []
  #   jobs:
  #     - job: device_tests
  #       workspace:
  #         clean: all
  #       displayName: Device Tests
  #       pool:
  #         name:  $(macOSXVmPool)
  #         vmImage: $(macOSXVmImage)
  #       variables:
  #         devicetests.project: '$(System.DefaultWorkingDirectory)/src/Essentials/test/DeviceTests.iOS/Essentials.DeviceTests.iOS.csproj'
  #       strategy:
  #         matrix:
  #           v14_3:
  #             devicetests.device: ios-simulator-64_14.3
  #           # v10_3_1:
  #           #   devicetests.device: ios-simulator-64_10.3.1
  #       steps:
  #         - template: device-tests-steps.yml
  #           parameters:
  #             platform: ios

  # - stage: ios_handlers
  #   displayName: Handlers (iOS)
  #   dependsOn: []
  #   jobs:
  #     - job: device_tests
  #       workspace:
  #         clean: all
  #       displayName: Device Tests
  #       pool:
  #         name:  $(macOSXVmPool)
  #         vmImage: $(macOSXVmImage)
  #       variables:
  #         devicetests.project: '$(System.DefaultWorkingDirectory)/src/Core/tests/DeviceTests.iOS/Core.DeviceTests.iOS.csproj'
  #       strategy:
  #         matrix:
  #           v14_3:
  #             devicetests.device: ios-simulator-64_14.3
  #           # v10_3_1:
  #           #   devicetests.device: ios-simulator-64_10.3.1
  #       steps:
  #         - template: device-tests-steps.yml
  #           parameters:
  #             platform: ios
