stages:
  - stage: nuget_signing
    dependsOn: pack_net6
    displayName: Sign Nuget
    variables:
      MicrosoftMauiGraphicsVersion: $[ stageDependencies.pack_net6.pack_net6_Windows.outputs['PackMaui.MicrosoftMauiGraphicsVersion'] ]
      MicrosoftWindowsAppSDKPackageVersion: $[ stageDependencies.pack_net6.pack_net6_Windows.outputs['PackMaui.MicrosoftWindowsAppSDKPackageVersion'] ]
      MicrosoftWindowsSDKBuildToolsPackageVersion: $[ stageDependencies.pack_net6.pack_net6_Windows.outputs['PackMaui.MicrosoftWindowsSDKBuildToolsPackageVersion'] ]
    jobs:
      - template: sign-artifacts/jobs/v2.yml@xamarin-templates
        parameters:
          signType: Real
          teamName: $(TeamName)
          usePipelineArtifactTasks: false
          targetFolder: $(Build.ArtifactStagingDirectory)/nuget/signed
          signedArtifactName: nuget
          signedArtifactPath: signed
          displayName: Sign Phase
          condition: and(succeeded(), or(eq(variables['Sign'], 'true'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), or(startsWith(variables['Build.SourceBranch'],'refs/tags/'),  startsWith(variables['Build.SourceBranch'],'refs/heads/release/') ))))

      - template: nuget-msi-convert/job/v2.yml@xamarin-templates
        parameters:
          yamlResourceName: xamarin-templates
          artifactName: nuget
          artifactPatterns: |
            **/signed/*.nupkg
          artifactPath: signed
          propsArtifactName: nuget
          signType: Real
          preConvertSteps:
            - template: download-library-nuget.yml
              parameters:
                id: Microsoft.Maui.Graphics
                version: $(MicrosoftMauiGraphicsVersion)
                sources: [ 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json' ]
            - template: download-library-nuget.yml
              parameters:
                id: Microsoft.Maui.Graphics.Win2D.WinUI.Desktop
                version: $(MicrosoftMauiGraphicsVersion)
                sources:
                  - 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json'
                  - 'https://api.nuget.org/v3/index.json'
            - template: download-library-nuget.yml
              parameters:
                id: Microsoft.WindowsAppSDK
                version: $(MicrosoftWindowsAppSDKPackageVersion)
            - template: download-library-nuget.yml
              parameters:
                id: Microsoft.Windows.SDK.BuildTools
                version: $(MicrosoftWindowsSDKBuildToolsPackageVersion)
